apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-que1
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ekgk-tenant/rhtap-demo-app/hacbs-test-project-que1@sha256:d1bd7b05366fbce0488f356e93e17ec52a9b7bea1e3e1e571767e8c0c30e334f
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
