apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-que1
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ekgk-tenant/rhtap-demo-app/hacbs-test-project-que1@sha256:7bf53119f64a48e855a2bd1bdb3293fe2b6754b992c2dbeb99b324186ede8699
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
