apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-que1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-que1
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-que1
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-que1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-que1
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ekgk-tenant/rhtap-demo-app/hacbs-test-project-que1@sha256:7bf53119f64a48e855a2bd1bdb3293fe2b6754b992c2dbeb99b324186ede8699
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
